### ISSUE TITLE
Chef attributes

### ISSUE THREAD

**Issue by tjarvstrand** [conjur-cookbooks/conjur-host-identity-chef#1]
Hi,

I have just started playing around with Conjur and I may have misunderstood how things work, but shouldn't the ssl certificate and the host factory token be kept secret? If they are set as attributes on the node object, the values will be available to anyone that has read access on the chef server.

BR

**Comment by kgilpin** [comment]
Hi. This is a relatively new feature so the documentation may not be as thorough as it could be. 

First, if you want to launch machines using a different mechanism (like cloud formation or a custom VM launcher) then you don't have to use Chef to create host identity. 

But if Chef is launching machines (eg via knife) then it needs to have a way to create host identity and give privileges to the host (via layer membership, typically). Therefore there needs to be some credential that gives Chef this ability. 

The host factory token is designed to be the minimal possible credential that you can give to Chef, that enables it to create and privilege a host. You can think of it as similar to the Chef validation.pem : a bootstrap credential. Only it's much more tightly scoped.  

Host factory token has the following designed advantages:

1) Separation of duties
Having access to the token enables any person or code to create a new host with defined privileges; but not to modify those privileges or change the token itself. 

2) Least privilege
The token is designed to convey a very specific ability (create a host with defined layer membership) and nothing more

3) Audit
Every use of the token is recorded

4) Time limited
An expiration is built into the token. For sensitive layers, create short lived tokens and rotate them frequently (eg every hour)

5) Limited number of uses
A token may be created with a built in number of "charges" (as few as one). After this the token is useless. 

I hope you find this helpful!

**Comment by kgilpin** [comment]
Oh by the way, the SSL certificate is not a secret. It's a public counterpart to the SSL private key held by the conjur server(s).

**Comment by tjarvstrand** [comment]
Thank you for your quick response! 

We're looking at a scenario where we will spin up new machines using several different mechanisms (manually, Jenkins automation, autoscaling, etc) and on multiple backends (atm. Amazon EC2 and an internal CloudStack instance). The common denominator is that once up, the machine will be provisioned using Chef.

It's good that the certificate is public, that way it can be configured in the machine's environment. That certificate will be the same for all connections to the same api endpoint, right?

It still sounds to me as though you wouldn't want to configure the host factory token using a chef attribute, since that would leave secret information easily available on the chef server. Expiring the token would render the instance unable to reconfigure itself. so it's not really an option while the instance is alive. Wouldn't it be more secure to allow the automation tool to put the secret onto the machine in a file and then point to that file using a chef attribute?

**Comment by kgilpin** [comment]
> It's good that the certificate is public, that way it can be configured in
> the machines environment. That will certificate be the same for all
> connections to the same api endpoint, right?

Yes, the cert will be valid for all Conjur servers in your environment.
When you make a standby master or follower, the new machine gets its own
certificate, but it's derived from the root certificate.

It still sounds to me as though you wouldn't want to configure the host

> factory token using a chef attribute, since that would leave secret
> information easily available on the chef server.

It's fine to make the token available on the machine some other way. For
example, Jenkins could place it on the machine, a person could put it
there, or the autoscaling configuration could know how to place it there.

Expiring the token would render the instance unable to reconfigure itself.

> so it's not really an option while the instance is alive.

Once the machine has obtained its own identity from the token, it never
uses the token again. So it's not a problem to expire tokens that have been
used.

> Wouldn't it be more secure to allow the automation tool to put the secret
> onto the machine in a file and then point to that file using a chef
> attribute?

This would be fine too. The question comes down to "who do you trust to see
the tokens"? If you have more trust in people (and code) with access to the
automation tool than you do with the Chef server, then the automation tool
is a better place to "source" the tokens.

Also, for development purposes you may have tokens that are not very
secret, because they are not used for production or to create production
artifacts.
- kevin

On Sun, Oct 19, 2014 at 4:20 AM, Thomas Järvstrand <notifications@github.com
